"""
config.py -- Simulation parameter configuration.

All tunable parameters are centralized here for easy management.
"""

from dataclasses import dataclass
import numpy as np

from .models import BaseModel, get_model


@dataclass
class SimulationConfig:
    """Simulation configuration for IV regression.

    Data generating process (general):
        y  = g(theta*; x) + c + eps_y
        x  = gamma*^T z   + c + eps_x

    where c is the confounding term (endogeneity source),
    and z is the instrument (uncorrelated with c, eps_y, eps_x).
    """

    # --- Model ---
    model_name: str = "linear"   # name of the structural model g(theta; x)

    # --- Random seed ---
    seed: int = 42

    # --- Data dimensions ---
    d_x: int = 5          # dimension of explanatory variable x
    d_z: int = 5          # dimension of instrument z

    # --- True parameters (auto-generated in __post_init__) ---
    theta_star: np.ndarray = None   # g(theta*; x), generated by model
    gamma_star: np.ndarray = None   # h(gamma*; z) = gamma*^T z
    model: BaseModel = None         # the model instance

    # --- Noise / distribution parameters ---
    mean_z: float = 0.0   # mean of instrument z (per component)
    sigma_z: float = 1.0  # std of instrument z
    sigma_c: float = 0.5  # std of confounding term c
    sigma_y: float = 0.3  # std of true noise eps_y
    sigma_x: float = 0.3  # std of true noise eps_x (per component)

    # --- Algorithm parameters ---
    # TOSG-IVaR
    tosg_lr: float = 0.01       # initial learning rate
    tosg_lr_decay: float = 0.5  # decay exponent: alpha_t = lr / t^decay

    # First-Order SLIM
    slim_lr: float = 0.01
    slim_lr_decay: float = 0.5
    slim_B_M: int = 1          # batch size for Jacobian estimate M̃
    slim_B_m: int = 1          # batch size for moment estimate m̃
    slim_W_type: str = "identity"  # "identity", "random", "custom"

    # OTSG-IVaR
    otsg_theta_lr: float = 0.01      # learning rate for theta
    otsg_theta_lr_decay: float = 0.5
    otsg_gamma_lr: float = 0.01      # learning rate for gamma (first-stage)
    otsg_gamma_lr_decay: float = 0.5

    # Distance Covariance Optimization (DCO)
    dcov_lr: float = 0.01            # initial learning rate
    dcov_lr_decay: float = 0.5       # decay exponent
    dcov_B: int = 64                 # batch size for dCov estimate

    # --- Training ---
    n_iterations: int = 100000  # iterations per run (same for all algorithms)
    verbose_every: int = 50000  # print progress every N iterations

    # --- Repetition ---
    n_repeats: int = 10      # number of independent runs

    def __post_init__(self):
        """Initialize model, true parameters, and dimension consistency."""
        rng = np.random.default_rng(self.seed)

        # Instantiate the structural model
        if self.model is None:
            self.model = get_model(self.model_name)

        # Generate true theta* from the model
        if self.theta_star is None:
            self.theta_star = self.model.true_params(rng, self.d_x)

        # Generate first-stage parameters
        if self.gamma_star is None:
            self.gamma_star = rng.normal(0, 1, size=(self.d_z, self.d_x))

    # ------------------------------------------------------------------
    # Derived properties
    # ------------------------------------------------------------------

    @property
    def d_theta(self) -> int:
        """Number of parameters (derived from model)."""
        return self.model.param_dim(self.d_x)


# ---------------------------------------------------------------------------
# Preset configurations
# ---------------------------------------------------------------------------

def default_config() -> SimulationConfig:
    """Default configuration (linear model)."""
    return SimulationConfig()


def low_noise_config() -> SimulationConfig:
    """Low-noise configuration (easier convergence)."""
    return SimulationConfig(
        sigma_c=0.2,
        sigma_y=0.1,
        sigma_x=0.1,
        n_iterations=1_000_000,
    )


def quadratic_config() -> SimulationConfig:
    """Quadratic model configuration."""
    return SimulationConfig(
        model_name="quadratic",
        d_x=4,
        d_z=4,
        sigma_c=0.3,
        sigma_y=0.2,
        sigma_x=0.2,
        n_iterations=1_000_000,
    )


def poly_config(degree: int = 2) -> SimulationConfig:
    """Polynomial model configuration."""
    return SimulationConfig(
        model_name=f"poly{degree}",
        d_x=3,
        d_z=3,
        sigma_c=0.2,
        sigma_y=0.1,
        sigma_x=0.1,
        n_iterations=1_000_000,
    )
